services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: booksportal-mssql
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
      MSSQL_PID: "Developer"
      MSSQL_TCP_PORT: "1433"
    volumes:
      - mssql-data:/var/opt/mssql
    ports:
      - "127.0.0.1:1433:1433"
    mem_limit: 3g

volumes:
  mssql-data:

networks:
  default:
    external: true
    name: coolify